# Changes here will be overwritten by Copier
_commit: 3ef9a65
_src_path: https://github.com/nialov/nialov-py-template.git
classifier: 'Topic :: Scientific/Engineering :: GIS'
description: Python package for stuff.
email: nikolasovaskainen@gmail.com
full_name: Nikolas Ovaskainen
github_account: nialov
keyword: data
package: paperai
year: 2020
